POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRpbGFtIiwiaWQiOiI2NWFiOGQwYTJhMWQwNzc5Zjg2YmQzN2YiLCJpYXQiOjE3MDU5NDE3ODd9.i9R50TAgM_Z8ECgMUhLQdLS9bjycDchTsybqvzq0iD0

{
    "title": "Eka plogh",
    "author": "Timo Lamminen",
    "url": "eka.com/polg",
    "likes": 123
}